version: '3.4'
services:
  postgres:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=App
      - PGDATA:/tmp

    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #   - ${DATA_PATH:-./data}:/var/lib/postgresql/data
  App-WebApi:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=https://+:443;http://+:80
    - ASPNETCORE_HTTPS_PORT=443
    ports:
     - "7501:80"
volumes:
  postgres_data:
    external: false
